# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "cleanerBotA"
  limits:
    linear: [0.7, 0.5] # velocity, acceleration
    angular: [0.4, 1.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 1.0 # radius in m
    vicinity: 1.2 # radius in m
  reversible: False # whether robots in this fleet can reverse
  # TODO Update battery parameters with actual specs
  battery_system:
    voltage: 24.0 # V
    capacity: 20.0 # Ahr
    charging_current: 10.0 # A
  mechanical_system:
    mass: 70.0 # kg
    moment_of_inertia: 40.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 100.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.20 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: False
    delivery: False
  actions: ["clean"]
  finishing_request: "park" # [park, charge, nothing]
  robots:
    cleanerBotA_0:
      charger: "charger_cleanerBotA_0"
    cleanerBotA_1:
      charger: "charger_cleanerBotA_1"
    cleanerBotA_2:
      charger: "charger_cleanerBotA_2"

fleet_manager:
  ip: "127.0.0.1"
  port: 22013
  user: "some_user"
  password: "some_password"
  robot_state_update_frequency: 10.0
  action_paths:
    clean:
      CD2027CW:
        map_name: "L0"
        path: [ [52.01, -140.18, 0.0],
                [52.59, -136.46, 1.57],
                [52.01, -140.18, 0.0] ]
        finish_waypoint: "CD2027CW"
      CD1022CW:
        map_name: "L0"
        path: [ [49.76, -57.46, 0.0],
                [44.85, -58.24, 1.57],
                [49.76, -57.46, 0.0] ]
        finish_waypoint: "CD1022CW"
      CD1023CW:
        map_name: "L0"
        path: [ [49.58, -48.9, 0.0],
                [49.58, -51.76, 1.57],
                [49.58, -48.9, 0.0] ]
        finish_waypoint: "CD1023CW"
      CD2028CW:
        map_name: "L0"
        path: [ [45.21, -140.07, 0.0],
                [45.79, -135.99, 1.57],
                [45.21, -140.07, 0.0] ]
        finish_waypoint: "CD2028CW"
      CD2104CW:
        map_name: "L1"
        path: [ [45.05, -140.18, 0.0],
                [45.98, -136.06, 1.57],
                [45.05, -140.18, 0.0] ]
        finish_waypoint: "CD2104CW"
      CD2103CW:
        map_name: "L1"
        path: [ [51.74, -140.79, 0.0],
                [52.46, -136.93, 1.57],
                [51.74, -140.79, 0.0] ]
        finish_waypoint: "CD2103CW"
      CD1118CW:
        map_name: "L1"
        path: [ [49.88, -49.26, 0.0],
                [50.13, -53.45, 1.57],
                [49.88, -49.26, 0.0] ]
        finish_waypoint: "CD1118CW"
      CD1117CW:
        map_name: "L1"
        path: [ [51.42, -58.28, 0.0],
                [47.91, -57.89, 1.57],
                [51.42, -58.28, 0.0] ]
        finish_waypoint: "CD1117CW"
      CD1217CW:
        map_name: "L2"
        path: [ [49.64, -49.07, 0.0],
                [48.89, -51.82, 1.57],
                [49.64, -49.07, 0.0] ]
        finish_waypoint: "CD1217CW"
      CD1216CW:
        map_name: "L2"
        path: [ [49.89, -57.98, 0.0],
                [44.06, -58.34, 1.57],
                [49.89, -57.98, 0.0] ]
        finish_waypoint: "CD1216CW"
      CD2204CW:
        map_name: "L2"
        path: [ [45.38, -140.21, 0.0],
                [46.42, -135.77, 1.57],
                [45.38, -140.21, 0.0] ]
        finish_waypoint: "CD2204CW"
      CD2203CW:
        map_name: "L2"
        path: [ [51.72, -139.57, 0.0],
                [51.61, -136.31, 1.57],
                [51.72, -139.57, 0.0] ]
        finish_waypoint: "CD2203CW"
      CD2303CW:
        map_name: "L3"
        path: [ [45.298, -139.95, 0.0],
                [46.31, -135.95, 1.57],
                [45.298, -139.95, 0.0] ]
        finish_waypoint: "CD2204CW"
      CD2304CW:
        map_name: "L3"
        path: [ [51.71, -139.25, 0.0],
                [51.57, -136.30, 1.57],
                [51.71, -139.25, 0.0] ]
        finish_waypoint: "CD2304CW"
      CD1316CW:
        map_name: "L3"
        path: [ [51.29, -57.92, 0.0],
                [45.33, -58.24, 1.57],
                [51.29, -57.92, 0.0] ]
        finish_waypoint: "CD1316CW"
      CD1317CW:
        map_name: "L3"
        path: [ [49.75, -48.81, 0.0],
                [49.61, -52.14, 1.57],
                [49.75, -48.81, 0.0] ]
        finish_waypoint: "CD1317CW"

