# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "tinyRobot"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
  actions: ["teleop"] # Actions this robot can perform
  finishing_request: "charge" # After completing tasks, request charging or parking
  use_parking_reservations: True
  reassign_task_interval: 120 # seconds, specify how often a task reassignment should be triggered in the fleet
  robots:
    tinyRobot1:
      charger: "tinyRobot1_charger" # Charging station name for tinyRobot1
      finishing_request: # Optional robot-specific finishing request
        type: "charge" # Robot should go to charge after finishing tasks
      responsive_wait: False # No responsive waiting for this robot
      initial_position: [50, 50] # Robot starting position on the map

fleet_manager:
  ip: "127.0.0.1"
  port: 22011
  user: "some_user"
  password: "some_password"

